---
- name: Remove old Grafana repo
  file:
    path: /etc/apt/sources.list.d/grafana.list
    state: absent

- name: Clean apt cache
  command: apt-get clean
  changed_when: false

- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - wget
      - gnupg
    state: present
    update_cache: yes

- name: Create keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Grafana GPG key
  get_url:
    url: https://apt.grafana.com/gpg-full.key
    dest: /etc/apt/keyrings/grafana.asc
    mode: '0644'

- name: Add Grafana repository
  copy:
    dest: /etc/apt/sources.list.d/grafana.list
    content: |
      deb [signed-by=/etc/apt/keyrings/grafana.asc] https://apt.grafana.com stable main
    mode: '0644'

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Grafana
  apt:
    name: grafana
    state: present

- name: Start Grafana
  systemd:
    name: grafana-server
    enabled: yes
    state: started
